import {
    AddressBook,
    Airplane,
    Alarm,
    AlignBottomSimple,
    AlignCenterHorizontalSimple,
    AlignCenterVerticalSimple,
    AlignLeftSimple,
    AlignRightSimple,
    AlignTopSimple,
    AnchorSimple,
    Archive,
    Armchair,
    ArrowArcLeft,
    ArrowArcRight,
    ArrowCounterClockwise,
    ArrowDown,
    ArrowDownLeft,
    ArrowFatDown,
    ArrowFatUp,
    ArrowLeft,
    ArrowLineDown,
    ArrowLineUp,
    ArrowLineUpRight,
    ArrowRight,
    ArrowsInSimple,
    ArrowsOutCardinal,
    ArrowsOutSimple,
    ArrowsSplit,
    ArrowUp,
    ArrowUpLeft,
    ArrowUpRight,
    Article,
    AsteriskSimple,
    At,
    Backspace,
    Bell,
    BellRinging,
    BellSlash,
    BookmarkSimple,
    BracketsCurly,
    Briefcase,
    Broadcast,
    Calendar,
    Camera,
    CameraSlash,
    CellSignalFull,
    CellSignalLow,
    CellSignalMedium,
    CellSignalSlash,
    ChartLine,
    ChatCircle,
    Check,
    CirclesFour,
    ClipboardText,
    Copy,
    Crown,
    DotsThree,
    Equalizer,
    FileDoc,
    Flag,
    GearSix,
    Hand,
    Link,
    List,
    Lock,
    LockOpen,
    MagnifyingGlass,
    MapPin,
    Microphone,
    MicrophoneSlash,
    Minus,
    Paperclip,
    PaperPlaneTilt,
    Pen,
    PhoneSlash,
    Plus,
    PushPin,
    PushPinSlash,
    Shield,
    ShieldSlash,
    ShieldStar,
    Stack,
    Sun,
    Tag,
    Trash,
    TreeStructure,
    UserCircle,
    UserCirclePlus,
    Users,
    VirtualReality,
    Webcam,
    WebcamSlash,
    X
} from 'phosphor-svelte';

export default {
    'address-book': AddressBook,
    'airplane': Airplane,
    'alarm': Alarm,
    'align-bottom': AlignBottomSimple,
    'align-center-horizontal': AlignCenterHorizontalSimple,
    'align-center-vertical': AlignCenterVerticalSimple,
    'align-left': AlignLeftSimple,
    'align-right': AlignRightSimple,
    'align-top': AlignTopSimple,
    'anchor': AnchorSimple,
    'archive': Archive,
    'armchair': Armchair,
    'arrow-arc-left': ArrowArcLeft,
    'arrow-arc-right': ArrowArcRight,
    'arrow-down': ArrowDown,
    'arrow-down-left': ArrowDownLeft,
    'arrow-download': ArrowFatDown,
    'arrow-left': ArrowLeft,
    'arrow-line-down': ArrowLineDown,
    'arrow-line-up': ArrowLineUp,
    'arrow-link': ArrowLineUpRight,
    'arrow-refresh': ArrowCounterClockwise,
    'arrow-right': ArrowRight,
    'arrow-up': ArrowUp,
    'arrow-up-left': ArrowUpLeft,
    'arrow-up-right': ArrowUpRight,
    'arrow-upload': ArrowFatUp,
    'arrows-in': ArrowsInSimple,
    'arrows-move': ArrowsOutCardinal,
    'arrows-out': ArrowsOutSimple,
    'arrows-split': ArrowsSplit,
    'article': Article,
    'asterisk': AsteriskSimple,
    'at': At,
    'backspace': Backspace,
    'bell': Bell,
    'bell-ringing': BellRinging,
    'bell-slash': BellSlash,
    'bookmark': BookmarkSimple,
    'brackets': BracketsCurly,
    'briefcase': Briefcase,
    'broadcast': Broadcast,
    'calendar': Calendar,
    'camera': Camera,
    'camera-off': CameraSlash,
    'chart': ChartLine,
    'chat': ChatCircle,
    'chat-send': PaperPlaneTilt,
    'check': Check,
    'clipboard': ClipboardText,
    'close': X,
    'copy': Copy,
    'crown': Crown,
    'dashboard': CirclesFour,
    'equalizer': Equalizer,
    'file-doc': FileDoc,
    'flag': Flag,
    'hand': Hand,
    'kebab-menu': DotsThree,
    'link': Link,
    'list': List,
    'lock': Lock,
    'lock-open': LockOpen,
    'map-pin': MapPin,
    'mic': Microphone,
    'mic-off': MicrophoneSlash,
    'minus': Minus,
    'paperclip': Paperclip,
    'pen': Pen,
    'phone-slash': PhoneSlash,
    'plus': Plus,
    'push-pin': PushPin,
    'push-pin-off': PushPinSlash,
    'search': MagnifyingGlass,
    'settings': GearSix,
    'shield': Shield,
    'shield-off': ShieldSlash,
    'shield-star': ShieldStar,
    'signal-high': CellSignalFull,
    'signal-low': CellSignalLow,
    'signal-mid': CellSignalMedium,
    'signal-none': CellSignalSlash,
    'stack': Stack,
    'tag': Tag,
    'theme': Sun,
    'trash': Trash,
    'tree': TreeStructure,
    'user': UserCircle,
    'user-add': UserCirclePlus,
    'user-list': Users,
    'vr': VirtualReality,
    'webcam': Webcam,
    'webcam-off': WebcamSlash
};
