name: Deploy services
on:
  push:
    branches:
      - master
jobs:

  # Unit testing for all packages
  tests:
    uses: ./.github/workflows/deploy_tests.yml

  # Build and deploy Peer server
  peer:
    needs: [ tests ]
    uses: ./.github/workflows/deploy_peer.yml
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_PKEY: ${{ secrets.SSH_PKEY }}

  # Build and deploy API server with sockets
  api:
    needs: [ tests ]
    uses: ./.github/workflows/deploy_api.yml
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_PKEY: ${{ secrets.SSH_PKEY }}

  # Build and deploy static server with client
  static:
    needs: [ tests ]
    uses: ./.github/workflows/deploy_static.yml
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_PKEY: ${{ secrets.SSH_PKEY }}

  # Finish pipeline with restarting services
  finish:
    needs: [ peer, api, static ]
    uses: ./.github/workflows/deploy_finish.yml
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_PKEY: ${{ secrets.SSH_PKEY }}
